BookStore/Models/Genre.cs
using System.ComponentModel.DataAnnotations;

namespace BookStore.Models
{
    public class Genre
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(100)]
        public string Name { get; set; }

        public List<Book> Books { get; set; }
       

    }
}

BookStore/Controllers/GenreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    [Authorize(Roles = nameof(Roles.Admin))]
    public class GenreController : Controller
    {
        private readonly IGenreRepository _genreRepository;
        public GenreController(IGenreRepository genreRepository)
        {
            _genreRepository = genreRepository;
        }
        public async Task<IActionResult> Index()
        {
            var genres = await _genreRepository.GetAllGenres();
            return View(genres);
        }

        public IActionResult AddGenre()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddGenre(GenreDTO genre)
        {
            if (!ModelState.IsValid)
            {
                return View(genre);
            }
            try
            {
                var GenreToAdd = new Genre
                {
                    Name = genre.GenreName,
                    Id = genre.Id
                };
                await _genreRepository.AddGenre(GenreToAdd);
                TempData["successMessage"] = "Genre added successfully";
                return RedirectToAction(nameof(AddGenre));
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Genre Count not be added! ";
                return View(genre);
            }
        }

        public async Task<IActionResult> UpdateGenre(int id)
        {
            var genre = await _genreRepository.GetGenreById(id);
            if (genre is null)
            {
                throw new InvalidOperationException($"Genre with Id {id} not found");
            }
            var GenreToUpdate = new GenreDTO
            {
                Id = genre.Id,
                GenreName = genre.Name
            };
            return View(GenreToUpdate);

        }
        [HttpPost]
        public async Task<IActionResult> UpdateGenre(GenreDTO genreYoUpdate)
        {
            if (!ModelState.IsValid)
            {
                return View(genreYoUpdate);
            }
            try
            {
                var genre = new Genre
                {
                    Name = genreYoUpdate.GenreName,
                    Id = genreYoUpdate.Id
                };
                await _genreRepository.UpdateGenre(genre);
                TempData["successMessage"] = "Genre updated successfully";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Genre Count not be updated! ";
                return View(genreYoUpdate);
            }

        }
        public async Task<IActionResult> DeleteGenre(int id)
        {
            try
            {
                var genre = await _genreRepository.GetGenreById(id);
                if (genre is null)
                {
                    throw new InvalidOperationException($"Genre with Id {id} not found");
                }
                await _genreRepository.DeleteGenre(genre);
                TempData["successMessage"] = "Genre deleted successfully";
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Genre Count not be deleted! ";
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

BookStore/Views/Genre/AddGenre.cshtml
@model GenreDTO
@{
}

<div style="width:50%">
    <h2>Add Genre</h2>
    <a asp-action="Index" asp-controller="Genre" class="btn btn-primary">Back</a>
    <form asp-action="AddGenre" >
        <div class="my-2">

            <label > Genre</label>
            <input type="text" asp-for="GenreName" class="form-control" />
            <span asp-validation-for="GenreName" class="text-danger"></span>
        </div>
        <div class="my-2">
            <button type="submit" class="btn btn-info">Add</button>
        </div>
           </form>
</div>

BookStore/Views/Genre/Index.cshtml
@model IEnumerable<Genre>
@{
    
}

<h2>Genres</h2>

<a asp-action="AddGenre" asp-controller="Genre" class="btn btn-primary ">Add More</a>
<table class="table table-striped my-2" >
    
        <tr>
            <th>Genre</th?
            <th>Action</th>
        </tr>

    
        @foreach (var genre in Model)
        {
            <tr>
                <td>@genre.Name</td>

                <td>
                    <a asp-action="UpdateGenre" asp-controller="Genre" asp-route-id="@genre.Id" class="btn btn-sm btn-success">Edit</a>
                    <a asp-action="DeleteGenre" asp-controller="Genre" asp-route-id="@genre.Id" class="btn btn-sm btn-danger" onclick="return window.confirm('Are you sure?')">Delete</a>
                </td>
            </tr>
        }
</table>
    

BookStore/Views/Genre/UpdateGenre.cshtml
@model GenreDTO
@{
}

<div style="width:50%">
    <h2>update Genre</h2>
    <a asp-action="Index" asp-controller="Genre" class="btn btn-primary">Back</a>
    <form asp-action="UpdateGenre">
        <input type="hidden" asp-for="Id"" />
        <div class="my-2">

            <label> Genre</label>
            <input type="text" asp-for="GenreName" class="form-control" />
            <span asp-validation-for="GenreName" class="text-danger"></span>
        </div>
        <div class="my-2">
            <button type="submit" class="btn btn-info">Update</button>
        </div>
    </form>
</div>